version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: plunt-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: plunt
      POSTGRES_PASSWORD: plunt_dev
      POSTGRES_DB: plunt
    volumes:
      - plunt_pgdata:/var/lib/postgresql/data

volumes:
  plunt_pgdata:
